// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPk3wbW-7msyI6_ssekB4V8qdUmlpQ-U',
    appId: '1:1001001295938:web:429981f050c0f9b7b84ddb',
    messagingSenderId: '1001001295938',
    projectId: 'task-organizer-1f0ae',
    authDomain: 'task-organizer-1f0ae.firebaseapp.com',
    databaseURL: 'https://task-organizer-1f0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-organizer-1f0ae.firebasestorage.app',
    measurementId: 'G-Y44FS3CL1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ4q0EbjjQqr4hv8BdLjSaiw68sJWRq_k',
    appId: '1:1001001295938:android:19ce21d7a7e1410fb84ddb',
    messagingSenderId: '1001001295938',
    projectId: 'task-organizer-1f0ae',
    databaseURL: 'https://task-organizer-1f0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-organizer-1f0ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjIzKoJ7HuZTdTcXWRZrZT3jeFa2uulY',
    appId: '1:1001001295938:ios:0e4f5a309efaf99bb84ddb',
    messagingSenderId: '1001001295938',
    projectId: 'task-organizer-1f0ae',
    databaseURL: 'https://task-organizer-1f0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'task-organizer-1f0ae.firebasestorage.app',
    iosBundleId: 'com.example.taskOrganizer',
  );

}